# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-20 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='database',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
