# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-20 10:10
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='database',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('data1_db', 'data1_db'), ('data2_db', 'data2_db'), ('data3_db', 'data3_db'), ('data4_db', 'data4_db')], max_length=35, null=True),
        ),
    ]
